export const roles = ['architect', 'developer', 'analyst', 'manager', ];
export const sides = ['fullstack', 'backend', 'frontend', 'mobile', 'other'];
export const importantSkills = [
  'Rails',
  'JavaScript',
  'Typescript',
  'PHP',
  'Node.js',
  // 'CSS',
  // 'Java',
  // 'Angular',
  'React',
  'AWS',
];
export const ignoreSkills = [
  // 'Haml',
  // 'RSpec',
  'Capybara',
  // 'Doctrine',
  'JS animations',
  'Babel',
  'JSX',
  'Webpack',
  'CSS animations',
  'Enzyme',
  'messaging',
  // 'microservices',
  'Mocha',
  // 'Rspec',
  // 'Selenium',
  'Gradle',
  'gulp',
  'Jade',
  'Responsive Design',
  'Minitest',
]
